plugins {
    id "com.android.application"
}

android {
    namespace "com.louisgreen.ipcheck"
    compileSdk 35

    defaultConfig {
        applicationId "com.louisgreen.ipcheck"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    sourceSets {
        main {
            assets.srcDirs += ["../../cmd/ipcheck/web"]
        }
    }
}

dependencies {
    implementation files("libs/ipcheckcore.aar")
}
